modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mes"
version="0.1.0"
displayName="Mekanism: Energy Singularity"
authors="Tau34"

description='''${mod_description}'''
[[dependencies.mes]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mes]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mes]]
modId="mekanismgenerators"
mandatory=true
versionRange="[10.4.0.14,)"
ordering="NONE"
side="BOTH"

[[dependencies.mes]]
modId="mekanism_extras"
mandatory=true
versionRange="[1.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mes]]
modId="mekanismscience"
mandatory=true
versionRange="[2.2,)"
ordering="NONE"
side="BOTH"